name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Ensure this is your AWS ECR region

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 522814707197.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t fastapi-app .
          docker tag fast-api:latest 522814707197.dkr.ecr.eu-north-1.amazonaws.com/fast-api:latest
          docker push 522814707197.dkr.ecr.eu-north-1.amazonaws.com/fast-api:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_VM_IP }}
          username: ${{ secrets.AWS_VM_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker $USER
            newgrp docker

            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 522814707197.dkr.ecr.eu-north-1.amazonaws.com
            docker pull 522814707197.dkr.ecr.eu-north-1.amazonaws.com/fast-api:latest
            docker stop fast-api || true
            docker rm fast-api || true
            docker run -d -p 8000:8000 --name fast-api 522814707197.dkr.ecr.eu-north-1.amazonaws.com/fast-api:latest
