name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_IMAGE }} .
          docker push ${{ vars.DOCKER_IMAGE }}

      - name: SSH into AWS VM and Deploy Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_VM_IP }}
          username: ${{ secrets.AWS_VM_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKER_IMAGE }}
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d -p 8000:8000 --name fastapi-app ${{ vars.DOCKER_IMAGE }}
